fixed the database Tests, wo that they now work on raspberry py with --remote option. Ie, when teh db is continually filled with data...

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -22,50 +22,54 @@ case "$#" in
 esac
 
 clear
+remote="ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER"
+
 case "$1" in
 
 	'-clean' )
 	echo "clean deploy now first removes the directory production/smartmeter on the target server...";
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'rm -rf production/smartMeter';
+	$remote 'rm -rf production/smartMeter';
 	;;
 
 	'-deploy2pi' | * )
 	echo "I will now try to deploy to pi@"$TARGETSERVER:$TARGET_SSH_PORT
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'uptime'
+	$remote 'uptime'
 
 
 	# copy the files to the pi
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'mkdir -p production/smartMeter';
+	$remote 'mkdir -p production/smartMeter';
 	rsync --exclude ".git" -R -ave 'ssh -p '$TARGET_SSH_PORT . pi@$TARGETSERVER:production/smartMeter/.
-#	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'mkdir -p public_html/smartMeter';
+#	$remote 'mkdir -p public_html/smartMeter';
 #	rsync -R -ave 'ssh -p '$TARGET_SSH_PORT src/main/client pi@$TARGETSERVER:public_html/smartMeter/.
 
 
 	# the smartMeter
 	echo "killing any running smartMeters"
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'sudo production/smartMeter/src/main/meter/rcdSmartMeter stop'
+	$remote 'sudo production/smartMeter/src/main/meter/rcdSmartMeter stop'
 	# the webServer
 	# kill any running server
 	echo "killing the currently running server..."
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'sudo production/smartMeter/src/main/webServer/rcdSmartMeterWebServer stop'
+	$remote 'sudo production/smartMeter/src/main/webServer/rcdSmartMeterWebServer stop'
 
 	echo "testing with mocha..."
-	echo "...and stopping on error"; set -e
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'cd production/smartMeter/src; sudo mocha --recursive'
+	echo "...and stopping on error"
+	set -e
+	$remote sudo rm -f /tmp/data/gotResults.json
+	$remote 'cd production/smartMeter/src/; sudo mocha --recursive'
 	# and removing the /tmp/smartMeterTestModeIsOn if necessary
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'sudo rm -f /tmp/smartMeterTestModeIsOn'
+	$remote 'sudo rm -f /tmp/smartMeterTestModeIsOn'
 
 
 	# install the server
     echo "installing the smartMeter bootstrap"
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'sudo production/smartMeter/src/main/meter/rcdSmartMeter rcinstall'
+	$remote 'sudo production/smartMeter/src/main/meter/rcdSmartMeter rcinstall'
 	echo "rcinstall the server bootstrap..."
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER 'sudo production/smartMeter/src/main/webServer/rcdSmartMeterWebServer rcinstall'
+	$remote 'sudo production/smartMeter/src/main/webServer/rcdSmartMeterWebServer rcinstall'
 
 
 	# start the smartMeter and the server
     echo "starting the smartMeter and the server..."
-	ssh -p $TARGET_SSH_PORT pi@$TARGETSERVER '(
+	$remote '(
 		sudo killall node;
 		cd production/smartMeter/src/main;
 		sudo meter/rcdSmartMeter start
